name: horizon
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.15+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: any
  scrollable_positioned_list:
  retry: ^3.0.1
  flutter_absolute_path: ^1.0.6
  progress_dialog: ^1.2.4
  flash:
  webview_flutter:
  expansion_tile_card:
  liquid_swipe: ^1.4.3
  syncfusion_flutter_calendar:
  simple_tooltip:
  percent_indicator: ^2.1.9+1
  mvc_pattern:
  global_configuration: ^1.6.0
  google_maps_flutter:
  flutter_google_places: ^0.2.6
  #  geolocator: ^7.0.1
#  multi_image_picker: ^4.7.13
  firebase_core:
  introduction_screen:

  video_player: ^0.10.12+5
  cool_alert: ^1.0.3
  flutter_uploader: ^1.2.0
  geolocator:

  intl:
  #  location: ^1.4.1
  google_maps_place_picker: ^0.9.1
  visibility_detector: ^0.1.5
  overlay_support: ^1.0.5
  html:
  rename: ^1.3.1
  path_provider: ^1.6.24
  shared_preferences: 0.5.3+4
  carousel_slider: any
  flutter_rating_bar: ^3.2.0+1
  like_button: ^1.0.4
  flutter_signature_pad: ^2.0.2
  flutter_datetime_picker: ^1.4.0
  sliding_up_panel: ^1.0.2
  modal_bottom_sheet: ^1.0.0+1
  device_info:
  url_launcher:
  permission_handler:
#  advance_pdf_viewer: any
  dropdown_search:

#  image_picker: 0.6.7+22
  group_button: ^1.3.0

  cached_network_image:

  #  badges: ^1.1.0
  flutter_sliding_up_panel: ^1.1.0+1
  socket_io_client: ^0.9.5
  flutter_local_notifications: ^1.4.4+1
  intl_phone_number_input: 0.5.1
  flutter_fadein: ^1.1.1
  fancy_bottom_navigation: ^0.3.2
  auto_size_text: ^2.1.0
  share: ^0.6.5+4
  #  image_picker: ^0.6.7+17
  firebase_messaging: ^7.0.3
  pin_code_fields:
  shimmer: ^1.1.2
  badges: ^1.2.0
  timeago:
  flutter_full_pdf_viewer: ^1.0.6
  awesome_dialog: ^1.3.2
  persistent_bottom_nav_bar:
  password_strength:
  flushbar: ^1.10.4
  audioplayers: ^0.15.1
  google_map_polyline: ^0.2.0
  location: ^2.3.5
  geocoder: ^0.2.1
  email_validator: '^1.0.6'
  country_list_pick:
  file_picker:
    path: file_picker-2.1.3
  pin_code_text_field: ^1.7.1
  toast: ^0.1.5
  time_range:
  intl_phone_field:
  flutter_chat_bubble: ^1.0.2
  cloud_firestore:
  dropdown_formfield: ^0.1.3
  table_calendar: 2.3.1
  syncfusion_flutter_signaturepad:
  rxdart:
  flutter:
    sdk: flutter
  google_fonts: ^0.3.5
  flutter_file_dialog:
  qr_code_scanner:

  bottom_navy_bar:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/cfg/
   - assets/bg/
   - assets/sounds/
   - assets/logo/
   - assets/guide/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts1/Poppins-Regular.ttf
    - family: sans
      fonts:
        - asset: assets/fonts/open-sans.regular.ttf
        - asset: assets/fonts/open-sans.light.ttf
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 200
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 800
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 900

    - family: zoom
      fonts:
        - asset: assets/icons/zoom.ttf
    - family: logout
      fonts:
        - asset: assets/icons/logout.ttf
    - family: empty_folder
      fonts:
        - asset: assets/icons/empty_folder.ttf
    - family: zoom_signature
      fonts:
        - asset: assets/icons/zoom_signature.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
