/// Flutter icons EmptyFolder
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EmptyFolder
///      fonts:
///       - asset: fonts/EmptyFolder.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EmptyFolder {
  EmptyFolder._();

  static const _kFontFam = 'empty_folder';
  static const String _kFontPkg = null;

  static const IconData empty_folder = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
